services:
  _defaults:
    autowire: true
    autoconfigure: true

  # Auto-register services in this bundle
  Tourze\DoctrineEntityRoutingBundle\Controller\:
    resource: '../../Controller/'
    tags: ['controller.service_arguments']

  Tourze\DoctrineEntityRoutingBundle\Service\:
    resource: '../../Service/'

  # Explicit definitions for testing
  Tourze\DoctrineEntityRoutingBundle\Controller\EntityMetadataController:
    tags: ['controller.service_arguments']